import { AgentProfile, Domain } from '../types'

const AGENT_COMPETENCE_HINTS: Record<string, string[]> = {
  fisioterapista: [
    'schiena',
    'lombalgia',
    'sciatica',
    'postura',
    'riabilitazione',
    'muscolo',
    'collo',
    'cervicale',
    'torcicollo',
    'contrattura',
    'strappo',
    'spalla',
    'gomito',
    'polso',
    'anca',
    'ginocchio',
    'caviglia',
    'tendinite',
    'fascite',
    'dolore',
    'trapezio',
    'nervo',
    'infiammazione',
    'irradiazione',
  ],
  fisiatra: [
    'schiena',
    'dolore',
    'articolazione',
    'riabilitazione',
    'colonna',
    'muscolo',
    'collo',
    'cervicale',
    'lombari',
    'nervo',
    'formicolio',
    'ernia',
    'discopatia',
    'protocollo',
    'recupero',
  ],
  'medico-dello-sport': [
    'infortunio',
    'recupero',
    'muscolo',
    'allenamento',
    'sport',
    'prestazione',
    'agonismo',
    'idoneità',
  ],
  cardiologo: [
    'cuore',
    'tachicardia',
    'pressione',
    'palpitazioni',
    'torace',
    'aritmia',
    'fibrillazione',
    'angina',
    'colesterolo',
    'trigliceridi',
    'infarto',
    'sincope',
    'affanno',
  ],
  gastroenterologo: [
    'stomaco',
    'intestino',
    'reflusso',
    'nausea',
    'digestione',
    'bruciore',
    'acidità',
    'gastrite',
    'colite',
    'gonfiore',
    'stitichezza',
    'diarrea',
    'rettocolite',
    'crohn',
    'celiachia',
    'emorroidi',
    'colon',
  ],
  dermatologo: [
    'pelle',
    'rash',
    'eczema',
    'dermatite',
    'acne',
    'prurito',
    'macchia',
    'neo',
    'orticaria',
    'psoriasi',
    'forfora',
    'caduta',
    'capelli',
    'unghie',
    'cicatrice',
    'rossore',
  ],
  dietista: [
    'dieta',
    'pasto',
    'ricetta',
    'menu',
    'schema alimentare',
    'porzioni',
    'fabbisogno calorico',
    'calorie',
    'alimentazione',
    'macros',
    'deficit',
    'peso',
    'dimagrire',
    'ingrassare',
  ],
  endocrinologo: [
    'tiroide',
    'glicemia',
    'ormoni',
    'insulina',
    'metabolismo',
    'diabete',
    'ipotiroidismo',
    'ipertiroidismo',
    'testosterone',
    'estrogeni',
    'cortisolo',
    'surrenale',
    'ipofisi',
    'menopausa',
  ],
  psicologo: [
    'ansia',
    'umore',
    'stress',
    'panico',
    'depressione',
    'triste',
    'preoccupato',
    'angoscia',
    'fobia',
    'trauma',
    'lutto',
    'burnout',
    'autostima',
    'blocco',
    'emozioni',
  ],
  'biologo-nutrizionista': [
    'microbiota',
    'integratori',
    'vitamine',
    'minerali',
    'nutrienti',
    'supplementi',
    'antiossidanti',
    'carenze',
    'flora',
    'omega',
    'probiotici',
    'prebiotici',
    'magnesio',
    'ferro',
    'vitamina',
  ],
  dietologo: [
    'diabete',
    'colesterolo',
    'metabolismo',
    'celiachia',
    'sovrappeso',
    'dislipidemia',
    'dieta',
    'obesità',
    'resistenza insulinica',
    'patologia',
    'medica',
  ],
  psichiatra: [
    'psicofarmaci',
    'antidepressivi',
    'ansiolitici',
    'bipolare',
    'schizofrenia',
    'psicosi',
    'farmaci',
    'disturbo',
    'ossessivo',
    'compulsivo',
    'deliri',
    'allucinazioni',
    'mania',
  ],
  reumatologo: [
    'artrite',
    'reumatismi',
    'lupus',
    'fibromialgia',
    'articolazioni',
    'autoimmune',
    'artralgia',
    'gonfiore',
    'rigidità',
    'mattutina',
    'gotta',
    'spondilite',
    'sjogren',
  ],
  'sleep-coach': [
    'sonno',
    'insonnia',
    'dormire',
    'risvegli',
    'apnea',
    'melatonina',
    'circadiano',
    'sonnolenza',
    'stanchezza',
    'riposo',
    'notte',
    'russare',
  ],
  'persona-trainer': [
    'allenamento',
    'palestra',
    'esercizio',
    'workout',
    'forza',
    'resistenza',
    'stretching',
    'muscolatura',
    'cardio',
    'scheda',
    'riscaldamento',
    'progressione',
  ],
  mmg: [
    'febbre',
    'malessere',
    'visita',
    'ricetta',
    'esami',
    'farmaco',
    'sintomi',
    'influenza',
    'tosse',
    'raffreddore',
    'stanchezza',
    'generico',
    'curante',
    'certificato',
    'testa',
    'cefalea',
    'mal',
  ],
  chef: ['ricetta', 'cucina', 'piatto', 'ingredienti', 'preparazione', 'cottura', 'cucinare'],
  chinesologo: ['movimento', 'postura', 'ginnastica', 'esercizio', 'motoria', 'coordinazione'],
  'mental-coach': [
    'motivazione',
    'obiettivi',
    'focus',
    'resilienza',
    'mentalità',
    'performance',
    'disciplina',
    'abitudini',
    'procrastinazione',
  ],
  'relationship-coach': [
    'relazione',
    'coppia',
    'comunicazione',
    'partner',
    'conflitto',
    'famiglia',
    'amore',
    'separazione',
  ],
  'life-organizer': [
    'organizzazione',
    'priorità',
    'tempo',
    'produttività',
    'pianificazione',
    'agenda',
    'routine',
    'abitudini',
  ],
  // ── Nuovi specialisti ────────────────────────────────────────────────────
  neurologo: [
    'cefalea',
    'emicrania',
    'vertigini',
    'formicolio',
    'nervo',
    'neuropatia',
    'tremore',
    'epilessia',
    'convulsioni',
    'intorpidimento',
    'diplopia',
    'memoria',
    'concentrazione',
    'cervicale',
    'irradiazione',
    'dolore neuropatico',
    'sciatica',
    'radiculopatia',
  ],
  ortopedico: [
    'frattura',
    'osso',
    'protesi',
    'artrosi',
    'menisco',
    'legamento',
    'tendine',
    'lussazione',
    'distorsione',
    'scoliosi',
    'ernia',
    'artrite',
    'ginocchio',
    'anca',
    'spalla',
    'colonna',
    'vertebra',
    'disco',
    'trauma',
  ],
  urologo: [
    'urinare',
    'vescica',
    'prostata',
    'rene',
    'calcoli',
    'ematuria',
    'bruciore',
    'minzione',
    'incontinenza',
    'frequenza',
    'sessuale',
    'disfunzione',
    'fertilità',
  ],
  oculista: [
    'vista',
    'visione',
    'occhio',
    'miopia',
    'astigmatismo',
    'presbiopia',
    'cataratta',
    'glaucoma',
    'retina',
    'diplopia',
    'bruciore occhi',
    'lacrimazione',
    'occhio secco',
    'lenti',
    'occhiali',
  ],
  otorinolaringoiatra: [
    'orecchio',
    'udito',
    'acufeni',
    'naso',
    'sinusite',
    'rinite',
    'gola',
    'tonsille',
    'voce',
    'disfonia',
    'laringite',
    'faringite',
    'roncopatia',
    'russare',
    'vertigini',
    'epistassi',
    'sangue dal naso',
  ],
  pneumologo: [
    'respiro',
    'tosse',
    'asma',
    'bronchite',
    'polmoni',
    'dispnea',
    'fiato',
    'affanno',
    'saturazione',
    'bpco',
    'polmonite',
    'fumo',
    'tabagismo',
    'apnea',
    'russare',
    'catarro',
  ],
}

function textToTokens(text: string): Set<string> {
  return new Set(
    text
      .toLowerCase()
      .replace(/[^a-z0-9àèéìòù_\-\s]/gi, ' ')
      .split(/\s+/)
      .filter((t) => t.length > 2),
  )
}

export function selectAgentsForRequest(
  team: AgentProfile[],
  domain: Domain,
  maxAgents: number,
  allDomains: Domain[] = [],
  message = '',
): AgentProfile[] {
  const secondary = allDomains.filter((d) => d !== domain && d !== 'general')
  const lowerMessage = message.toLowerCase()
  const msgTokens = textToTokens(message)

  // Scoring is fully general — same rules for every agent:
  //   +4  primary domain match
  //   +1  'general' domain tag
  //   +2  each secondary domain match
  //   +2  agent id or displayName mentioned in message
  //   +3  per competence-hint keyword match
  // No hardcoded bonus for any specific agent group.
  const scored = team.map((a) => ({
    agent: a,
    score: (() => {
      let s = 0
      if (a.domainTags.includes(domain)) s += 4
      if (a.domainTags.includes('general')) s += 1
      for (const d of secondary) if (a.domainTags.includes(d)) s += 2
      if (lowerMessage.includes(a.id.toLowerCase())) s += 2
      if (lowerMessage.includes(a.displayName.toLowerCase())) s += 2

      const competenceHints = AGENT_COMPETENCE_HINTS[a.id] ?? []
      // Single-word hints use the fast token Set; multi-word hints fall back to substring search
      const competenceMatches = competenceHints.filter((h) =>
        h.includes(' ') ? lowerMessage.includes(h) : msgTokens.has(h),
      ).length
      if (competenceMatches > 0) s += competenceMatches * 3

      return s
    })(),
  }))

  // F3: Filter out low-confidence specialists. With the base domain score of +4,
  // a specialist that ONLY matches on domain (no competence hints, no name mention)
  // scores exactly 4. We keep them but cap the total to avoid flooding the pipeline.
  // Agents scoring ≤ 2 (only from secondary domain or 'general') are excluded to
  // prevent out-of-scope specialists (e.g. endocrinologo on a nutrition-only query).
  return scored
    .filter((x) => x.score > 2)
    .sort((a, b) => b.score - a.score || a.agent.id.localeCompare(b.agent.id))
    .slice(0, maxAgents)
    .map((x) => x.agent)
}
