export const specialistDisplayName: Record<string, string> = {
  intervistatore: 'Intervistatore',
  dietista: 'Dietista',
  personal_trainer: 'Personal Trainer',
  psicologo: 'Psicologo',
  mental_coach: 'Mental Coach',
  chef: 'Chef',
  fisioterapista: 'Fisioterapista',
  fisiatra: 'Fisiatra',
  medico_sport: 'Medico dello Sport',
  mmg: 'MMG',
  gastroenterologo: 'Gastroenterologo',
  chinesologo: 'Chinesologo',
  analista_contesto: 'Analista del Contesto',
}

export const specialistEmoji: Record<string, string> = {
  intervistatore: '🎙️',
  dietista: '🥗',
  personal_trainer: '💪',
  psicologo: '🧠',
  mental_coach: '🎯',
  chef: '👨‍🍳',
  fisioterapista: '🦴',
  fisiatra: '⚕️',
  medico_sport: '🏅',
  mmg: '🩺',
  gastroenterologo: '🫁',
  chinesologo: '🤸',
  analista_contesto: '🔍',
}
